### ISSUE TITLE
The type 'Object' is required here and is unavailable

### ISSUE THREAD

**Issue by TimLariviere** [fabulousfx/FSharp.Android.ResourceProvider#1]
I've been porting the logic of Xamarin.Android.FSharp.ResourceProvider to this new type provider:
- Compile Resource.designer.cs into a dll
- Load that dll for Reflection
- Feed the dll bytes and exported types to `ITypeProvider`

The dll gets compiled fine.
If I take a direct reference to that dll in the `net6.0-android` project, I can access all resources with no problem.

The issue happens when I use the Type Provider to load that dll.
```
FSharp.Android.ResourceProvider.Tests.fs(6,15):
error FS1108: The type 'Object' is required here and is unavailable. You must add a reference to assembly 'System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
```

I guess there must be some kind of wrong assemblies at the moment of reflection, and the type provider loads the wrong types.
But I tried to check the assembly locations and they are good.

@nosami Do you remember if you've got that kind of error while developing Xamarin.Android.FSharp.ResourceProvider?

**Comment by nosami** [comment]
I don't think I ever saw that error.

What happens if you add the CoreLib reference to the C# compilation?

**Comment by TimLariviere** [comment]
And I don't think the issue is with the C# compilation, given using the dll manually works perfectly well

**Comment by nosami** [comment]
Hmm, I see now. 

I think maybe it is because the IDE is using a different framework (not android).

This code was redirecting assemblies used at design time to ones used at runtime. Looks like you are missing this?
 https://github.com/xamarin/Xamarin.Android.FSharp.ResourceProvider/blob/87b7b0084d537fbc67e20aaf2a94d728ae171914/ResourceTypeProvider.fs#L111-L123

**Comment by nosami** [comment]
There are 2 frameworks.... the one used by the IDE process, and the one used by the mobile application.

Unfortunately, these will generally use different assemblies and some redirection is required.

**Comment by TimLariviere** [comment]
I tried this as well.
ReflectionOnly is not allowed on .NET Core (`ReflectionOnly loading is not supported on this platform`)
And no resolve events are raised when doing `Assembly.LoadFrom`...

**Comment by nosami** [comment]
What happens if you use `AppDomain.CurrentDomain.add_AssemblyResolve` instead of `AppDomain.CurrentDomain.add_ReflectionOnlyAssemblyResolve` and switch all the other usages of ReflectionOnly?

There was an issue with this in the past, but unfortunately I can't remember what.

**Comment by TimLariviere** [comment]
Yes, I meant I tried all `add_*Resolve` with all combination of `Assembly.*Load*`. No luck

**Comment by TimLariviere** [comment]
Even tried to create an AppDomain, but .NET Core forbids it

**Comment by nosami** [comment]
Without this, I think you are stuck.

When you use the type provider in the IDE, then you need to use the system assemblies that are used by the IDE target framework, not the system assemblies used by the mobile framework. One way or another, some redirection will be required.

**Comment by TimLariviere** [comment]
😢 

Well, I'll try to explore my other ideas then...
- Either parse the C# file with Roslyn to generate on the fly the provided types/fields/etc. via the TypeProvider
- Or create an MSBuild task to compile the C# file and somehow load it implicitly in the target project

**Comment by nosami** [comment]
> Or create an MSBuild task to compile the C# file and somehow load it implicitly in the target project

I seem to remember @dellis1972 attempting this a few years ago.

This can work but you would be forced to manually build after each change to the resources. Probably not a dealbreaker.

Personally, I would wait for Xamarin.Android to emit IL in MAUI.

**Comment by TimLariviere** [comment]
>Personally, I would wait for Xamarin.Android to emit IL in MAUI.

Ok. After the messages from @dellis1972, I feel better about F# and Android.

I'll just try my quick hack in the meantime using Roslyn syntax tree to support netfx and net6.0 apps.
Should be quick to do (at least I've confirmed that I didn't had the Object not available issue) and enough to cover 90% of the cases while waiting for the IL emiting.

**Comment by dellis1972** [comment]
For reference this is the PR which should help make this Type Provider redundant https://github.com/xamarin/xamarin-android/pull/6427. Note this will probably only be enabled by default for .net 6, once I get the PR complete.

**Comment by TimLariviere** [comment]
I went with the MSBuild way instead of TypeProvider.
Too many difficulties to get it working.

Please see https://github.com/fabulousfx/FSharp.Android.Resource instead
